### PR TITLE
add docker and docker compose, update seeder formatting

### PR DESCRIPTION
**Pull request by mtlaney**
﻿## Summary
Addresses Issue #1590 

Please note if fully resolves the issue per the acceptance criteria: Y

*Add dockerfile for frontend and server, add communications with docker-compose. To test locally run docker-compose up, after build you should be able to hit localhost:4200 and see the application and data*

## Impacted Areas of the Site
- config files

## This pull request changes...
- [ ] adds docker and docker compose locally, fixes formatting for seed file

## This pull request is ready to merge when...
- [ ] Feature branch is starts with the issue number
- [ ] Is connected to its original issue via zenhub 👇
- [ ] Tests have been updated 
- [ ] All tests are passing and meet coverage, linting, and accessibility requirements. And no security vulnerabilities ⚫️(Jenkins)
- [ ] Server actions captured by logs (manual)
- [ ] Documentation / readme.md updated (manual)
- [ ] API docs updated if need (manual)
- [ ] JSDocs updated (manual)
- [ ] This code has been reviewed by someone other than the original author

### CODE REVIEW

**Review by mwreiss — COMMENTED** [review]
@mtlaney looking at lines 6-8.  Can you obfuscate line 8? Specifically on the docker-compose.yml

**Comment by mtlaney** [comment]
> @mtlaney looking at lines 6-8. Can you obfuscate line 8? Specifically on the docker-compose.yml

Right now that's only for local setup, it doesn't house any of our env variables for dev/staging/prod. Those are the lines Ilaya will need to change to our VCAP variables or whatever env variable equivalent we're using for AWS.

**Comment by mwreiss** [comment]
@mtlaney  thank you, that is what I wanted to hear.

**Review by mwreiss — APPROVED** [review]
Thanks Mike.

**Pull request merged**
