### PR TITLE
Add docker-compose, Dockerfiles

### PR DESCRIPTION
**Pull request by mgwalker**
﻿## Summary

Adds Docker bits to quickly spin up a dev environment. This may not be useful to anyone but me, in which case let's ignore it and I can maintain the Docker stuff in a local branch rather than having it be part of the shared repo.

### CODE REVIEW

**Comment by mwreiss** [comment]
@mgwalker I would like to review and understand this a little further before this goes in.

**Comment by mgwalker** [comment]
Sure thing! If it'd be helpful, we could hop on a call for a few minutes sometime and I could walk you through it. It's just meant for use on local dev machines (and again, if I'm the only person it'd help, then let's just leave it out).

**Review by mtlaney — APPROVED** [review]

**Comment by mtlaney** [comment]
Looks good to me! love compose

What no local kubernetes cluster?
image

**Comment by mgwalker** [comment]
angry child shaking a hair brush

**Comment by mwreiss** [comment]
@mgwalker After further review this one is good from my perspective thanks.  I was thinking this would affect downstream but all is good since it helps with the local environment.

**Pull request closed without merging**
